//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightClubReports.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FightClubReports.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По дате.
        /// </summary>
        internal static string byDate {
            get {
                return ResourceManager.GetString("byDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По логину.
        /// </summary>
        internal static string byLogin {
            get {
                return ResourceManager.GetString("byLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По сумме.
        /// </summary>
        internal static string bySum {
            get {
                return ResourceManager.GetString("bySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По типу.
        /// </summary>
        internal static string byType {
            get {
                return ResourceManager.GetString("byType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить изменения.
        /// </summary>
        internal static string cancelChanges {
            get {
                return ResourceManager.GetString("cancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете информацию для отображения.
        /// </summary>
        internal static string chooseInfoForShow {
            get {
                return ResourceManager.GetString("chooseInfoForShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете тип информации для отображения.
        /// </summary>
        internal static string chooseInfoTypeForShow {
            get {
                return ResourceManager.GetString("chooseInfoTypeForShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бои.
        /// </summary>
        internal static string combats {
            get {
                return ResourceManager.GetString("combats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По типу.
        /// </summary>
        internal static string combatsByType {
            get {
                return ResourceManager.GetString("combatsByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин ниже.
        /// </summary>
        internal static string enterLogin {
            get {
                return ResourceManager.GetString("enterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин игрока в соответствующее поле.
        /// </summary>
        internal static string enterLoginInField {
            get {
                return ResourceManager.GetString("enterLoginInField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин игрока не введен.
        /// </summary>
        internal static string loginIsNotEntered {
            get {
                return ResourceManager.GetString("loginIsNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ни один вариант не выбран.
        /// </summary>
        internal static string noOneOptionIsNotSelected {
            get {
                return ResourceManager.GetString("noOneOptionIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан.
        /// </summary>
        internal static string notSpecified {
            get {
                return ResourceManager.GetString("notSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По алфавиту.
        /// </summary>
        internal static string playersByAlphabet {
            get {
                return ResourceManager.GetString("playersByAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По регистрации.
        /// </summary>
        internal static string playersByDate {
            get {
                return ResourceManager.GetString("playersByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По количеству боев.
        /// </summary>
        internal static string playersByNumberOfCombats {
            get {
                return ResourceManager.GetString("playersByNumberOfCombats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По количеству транзакций.
        /// </summary>
        internal static string playersByNumberOfTransactions {
            get {
                return ResourceManager.GetString("playersByNumberOfTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email валидны.
        /// </summary>
        internal static string playersByValidEmail {
            get {
                return ResourceManager.GetString("playersByValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения .
        /// </summary>
        internal static string saveChanges {
            get {
                return ResourceManager.GetString("saveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение прошло успешно.
        /// </summary>
        internal static string successfulSaving {
            get {
                return ResourceManager.GetString("successfulSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string sum {
            get {
                return ResourceManager.GetString("sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ лучших.
        /// </summary>
        internal static string topPlayers {
            get {
                return ResourceManager.GetString("topPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транзакции.
        /// </summary>
        internal static string transactions {
            get {
                return ResourceManager.GetString("transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По сумме.
        /// </summary>
        internal static string transactionsBySum {
            get {
                return ResourceManager.GetString("transactionsBySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
